name: Build Debug WASM
on: 
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Checkout Rive Renderer Repo
        uses: actions/checkout@v3
        with:
          repository: rive-app/rive-renderer
          path: ./wasm/submodules/rive-renderer
          ref: main
          
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.43
          actions-cache-folder: "emsdk-cache"
          
      - name: Configure venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          
      - name: Install premake
        run: |
          wget -q https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz
          tar -xf premake-5.0.0-beta2-linux.tar.gz
          sudo chmod a+x premake5
          sudo mv premake5 /usr/local/bin
          pip3 install ply

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
          
      - name: Build Debug WASM
        run: |
          cd js
          EMCC_DEBUG=1 ./build_wasm.sh
          
      - name: Upload Debug WASM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debug-wasm
          path: |
            js/build/**/*.wasm
          retention-days: 30
